[package]
name = "gsa_bevy"
version = "0.1.0"
edition = "2021"

[lib]
name = "engine"
path = "src/engine/lib.rs"

[[bin]]
name = "gsa_bevy"
path = "src/bin.rs"


[dependencies]
bevy = "0.11.3"
rand = "0.8.5"
noise = "0.8.2"